package com.itis.ganiev.baseproject

object CountryRepository {

    fun getCountries() = arrayListOf(
        Country(0,
            R.drawable.flag_austria,
            "Austria",
            "Vienna",
            "German",
            83879,
            8902600,
            "Euro",
            "Austria (officially the Republic of Austria) is a landlocked East Alpine country in the southern part of Central Europe. It is composed of nine federated states (Bundesländer), one of which is Vienna, Austria's capital and its largest city. It is bordered by Germany to the northwest; the Czech Republic to the north; Slovakia to the northeast; Hungary to the east; Slovenia and Italy to the south; and Switzerland and Liechtenstein to the west. Austria occupies an area of 83,879 km2 (32,386 sq mi) and has a population of nearly 9 million people. While German is the country's official language, many Austrians communicate informally in a variety of Bavarian dialects."
        ),
        Country(1,
            R.drawable.flag_belarus,
            "Belarus",
            "Minsk",
            "Belarusian, Russian",
            207595,
            9408400,
            "Belarusian ruble",
            "Belarus (officially the Republic of Belarus) and formerly known as Byelorussia or Belorussia (Russian: Белоруссия) is a landlocked country in Eastern Europe. It is bordered by Russia to the northeast, Ukraine to the south, Poland to the west, and Lithuania and Latvia to the northwest. Its capital and most populous city is Minsk. Over 40% of its 207,600 square kilometres (80,200 sq mi) is forested. Its major economic sectors are service industries and manufacturing. Until the 20th century, different states at various times controlled the lands of modern-day Belarus, including Kievan Rus', the Principality of Polotsk (11th to 14th centuries), the Grand Duchy of Lithuania, the Polish–Lithuanian Commonwealth, and the Russian Empire."
        ),
        Country(2,
            R.drawable.flag_belgium,
            "Belgium",
            "Brussels",
            "Dutch, French, German",
            30689,
            11492641,
            "Euro",
            "Belgium (officially the Kingdom of Belgium) is a country in Western Europe. It is bordered by the Netherlands to the north, Germany to the east, Luxembourg to the southeast, France to the southwest, and the North Sea to the northwest. It covers an area of 30,689 km2 (11,849 sq mi) and has a population of more than 11.5 million, making it the 22nd most densely populated country in the world and the 6th most densely populated country in Europe, with a density of 376 per square kilometre (970/sq mi). The capital and largest city is Brussels; other major cities are Antwerp, Ghent, Charleroi, Liège, Bruges, Namur, and Leuven."
        ),
        Country(3,
            R.drawable.flag_denmark,
            "Denmark",
            "Copenhagen",
            "Danish",
            42933,
            5824857,
            "Danish krone",
            "Denmark (officially the Kingdom of Denmark) is a Nordic country in Northern Europe. Denmark proper, which is the southernmost of the Scandinavian countries, consists of a peninsula, Jutland, and an archipelago of 443 named islands, with the largest being Zealand, Funen and the North Jutlandic Island. The islands are characterised by flat, arable land and sandy coasts, low elevation and a temperate climate. Denmark lies southwest of Sweden and south of Norway, and is bordered to the south by Germany. The Kingdom of Denmark is constitutionally a unitary state comprising Denmark proper and the two autonomous territories in the North Atlantic Ocean: the Faroe Islands and Greenland. Denmark has a total area of 42,924 km2 (16,573 sq mi), land area of 42,394 km2 (16,368 sq mi), and the total area including Greenland and the Faroe Islands is 2,210,579 km2 (853,509 sq mi), and a population of 5.82 million in Denmark proper (as of 2020)."
        ),
        Country(4,
            R.drawable.flag_finland,
            "Finland",
            "Helsinki",
            "Finnish, Swedish",
            338455,
            5528737,
            "Euro",
            "Finland (officially the Republic of Finland) is a Nordic country located in Northern Europe. Finland shares land borders with Sweden to the west, Russia to the east, and Norway to the north and is defined by the Gulf of Bothnia to the west and the Gulf of Finland to the south that are part of the Baltic Sea. Finland has a population of approximately 5.5 million, making it the 25th-most populous country in Europe. With an area of 338,455 square kilometres (130,678 sq mi), Finland is the eighth-largest country in Europe, and the most sparsely populated country in the European Union. Helsinki, the capital of Finland, is the largest city in the country."
        ),
        Country(5,
            R.drawable.flag_france,
            "France",
            "Paris",
            "French",
            640679,
            67081000,
            "Euro",
            "France (officially the French Republic) is a country consisting of metropolitan France in Western Europe and several overseas regions and territories. The metropolitan area of France extends from the Rhine to the Atlantic Ocean and from the Mediterranean Sea to the English Channel and the North Sea. It borders Belgium, Luxembourg and Germany to the northeast, Switzerland, Monaco and Italy to the east and Andorra and Spain to the south. The overseas territories include French Guiana in South America and several islands in the Atlantic, Pacific and Indian oceans. The country's 18 integral regions (five of which are situated overseas) span a combined area of 643,801 square kilometres (248,573 sq mi) and a total population of 67.07 million (as of May 2020). France is a unitary semi-presidential republic with its capital in Paris, the country's largest city and main cultural and commercial centre. Other major urban areas include Lyon, Marseille, Toulouse, Bordeaux, Lille and Nice. France, including its overseas territories, has the most time zones of any country, with a total of 12."
        ),
        Country(6,
            R.drawable.flag_germany,
            "Germany",
            "Berlin",
            "German",
            357022,
            83166711,
            "Euro",
            "Germany (officially the Federal Republic of Germany) is a country in Central and Western Europe. Covering an area of 357,022 square kilometres (137,847 sq mi), it lies between the Baltic and North seas to the north, and the Alps to the south. It borders Denmark to the north, Poland and the Czech Republic to the east, Austria and Switzerland to the south, and France, Luxembourg, Belgium and the Netherlands to the west."
        ),
        Country(7,
            R.drawable.flag_greece,
            "Greece",
            "Athens",
            "Greek",
            131957,
            10724599,
            "Euro",
            "Greece (officially the Hellenic Republic, known also as Hellas) is a country located in Southeast Europe. Its population is approximately 10.7 million as of 2018; Athens, the nation's capital, is its largest city, followed by Thessaloniki."
        ),
        Country(8,
            R.drawable.flag_iceland,
            "Iceland",
            "Reykjavík",
            "Icelandic",
            102775,
            364134,
            "Icelandic króna",
            "Iceland is a Nordic island country in the North Atlantic Ocean, with a population of 364,134 and an area of 103,000 km2 (40,000 sq mi), making it the most sparsely populated country in Europe. The capital and largest city is Reykjavík. Reykjavík and the surrounding areas in the southwest of the country are home to over two-thirds of the population. Iceland is volcanically and geologically active. The interior consists of a plateau characterised by sand and lava fields, mountains, and glaciers, and many glacial rivers flow to the sea through the lowlands. Iceland is warmed by the Gulf Stream and has a temperate climate, despite a high latitude just outside the Arctic Circle. Its high latitude and marine influence keep summers chilly, with most of the archipelago having a polar climate."
        ),
        Country(9,
            R.drawable.flag_ireland,
            "Ireland",
            "Dublin",
            "Irish, English",
            70273,
            4977400,
            "Euro",
            "Ireland (also known as the Republic of Ireland) is a country in north-western Europe occupying 26 of 32 counties of the island of Ireland. The capital and largest city is Dublin, which is located on the eastern side of the island. Around 40% of the country's population of 4.9 million people resides in the Greater Dublin Area. The sovereign state shares its only land border with Northern Ireland which is part of the United Kingdom. It is otherwise surrounded by the Atlantic Ocean, with the Celtic Sea to the south, St George's Channel to the south-east, and the Irish Sea to the east. It is a unitary, parliamentary republic. The legislature, the Oireachtas, consists of a lower house, Dáil Éireann, an upper house, Seanad Éireann, and an elected President (Uachtarán) who serves as the largely ceremonial head of state, but with some important powers and duties. The head of government is the Taoiseach (Prime Minister, literally 'Chief', a title not used in English), who is elected by the Dáil and appointed by the President; the Taoiseach in turn appoints other government ministers."
        ),
        Country(10,
            R.drawable.flag_italy,
            "Italy",
            "Rome",
            "Italian",
            301340,
            60317116,
            "Euro",
            "Italy (officially the Italian Republic) is a country consisting of a peninsula delimited by the Alps and surrounded by several islands. Italy is located in south-central Europe, and is considered part of western Europe. A unitary parliamentary republic with Rome as its capital, the country covers a total area of 301,340 km2 (116,350 sq mi) and shares land borders with France, Switzerland, Austria, Slovenia, and the enclaved microstates of Vatican City and San Marino. Italy has a territorial enclave in Switzerland (Campione) and a maritime exclave in Tunisian waters (Lampedusa). With around 60 million inhabitants, Italy is the third-most populous member state of the European Union."
        )
    )

}